FROM python
COPY . .
RUN pip install -r requirements.txt
ENV CONNECTION_STRING "EVENTHUBCONNECTIONSTRING"
ENV EVENTHUB_NAME "eventhub_name"
ENV WINDOW_SIZE 120
ENV WINDOW_INTERVAL 300
ENV TIME_INTERVAL 1
ENV BATCH_MESSAGES_NUMBER 1
CMD python setup.py